FROM python:3.10-slim

LABEL maintainer="matthew@resim.ai"

# Copy files
COPY requirements.txt .
COPY metrics_reader.py .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "metrics_reader.py"] 